Add missing projects to weekly test
canonical/solutions-engineering-automation pull request #11
Opened 2024-04-24 18:19 UTC by zxhdaze

Add missing projects to weekly test

2024-04-25 11:00 UTC, dashmage requested changes
We should skip adding bootstack-actions, layer-beats-base. Everything else LGTM :)

2024-04-25 11:00 UTC, dashmage commented on .github/workflows/weekly_tests.yaml
> +            branch: main
For bootstack-actions, we use `pull-request.yaml` as a reusable workflow file in other repos and is not something that needs to be run weekly.

2024-04-25 11:00 UTC, dashmage commented on .github/workflows/weekly_tests.yaml
> +            branch: master
The `ci.yaml` for layer-beats-base only contains lint and unit tests. So I don't think it deserves to be run weekly.

2024-05-01 07:05 UTC, rgildein approved these changes
LGTM, thanks

2024-05-02 17:27 UTC, aieri approved these changes

2024-05-03 01:35 UTC, jneo8 approved these changes

2024-05-03 12:12 UTC, dashmage approved these changes

2024-05-03 13:36 UTC, merged