fix(terraform): Fix wrong repo configuration
canonical/solutions-engineering-automation pull request #26
Opened 2024-06-04 10:53 UTC by jneo8

- For branch protection rule
  - Remove force_push_bypassers
  - Remove dismissal_restrictions
  - Set allows_force_pushes=false
- Add vulnerability_alerts=true for repo setting

2024-06-04 10:57 UTC, Pjack approved these changes
Thanks to adjust the configuration again based the [doc](https://docs.google.com/document/d/12dwn3lvewX4B5TJTjG1CwFpcr8-62Viy1o3B9Oe9Bhg/edit)

2024-06-04 10:58 UTC, Pjack requested changes

2024-06-04 10:58 UTC, Pjack commented on terraform-plans/main.tf
>    pull_request_bypassers = ["${var.owner}/soleng-admin"]
pull_request_bypassers 
This can be removed.

2024-06-05 03:25 UTC, Pjack approved these changes

2024-06-05 05:14 UTC, merged

2024-06-05 07:33 UTC, rgildein commented
FYI: Those settings were there to mimic what was possible before. Terraform will set "Do not allow bypassing the above settings ", so without any bypass even admin of repo should not do it.